package com.aieoms.rbac.service;

import com.aieoms.rbac.entity.Role;
import com.aieoms.rbac.entity.UserRole;
import com.aieoms.rbac.repository.RoleRepository;
import com.aieoms.rbac.repository.UserRoleRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RbacServiceTest {

    @Mock
    private RoleRepository roleRepository;

    @Mock
    private UserRoleRepository userRoleRepository;

    private RbacService rbacService;

    @BeforeEach
    void setUp() {
        rbacService = new RbacService(
                roleRepository,
                userRoleRepository
        );
    }

    @Test
    void initializeRoles_shouldCreateAllRolesWhenMissing() {

        when(roleRepository.existsByName(anyString()))
                .thenReturn(false);

        rbacService.initializeRoles();

        verify(roleRepository).save(argThat(role ->
                RbacService.ROLE_USER.equals(role.getName())
                        && "Standard authenticated user"
                        .equals(role.getDescription())
        ));

        verify(roleRepository).save(argThat(role ->
                RbacService.ROLE_OPERATOR.equals(role.getName())
                        && "Incident operations operator"
                        .equals(role.getDescription())
        ));

        verify(roleRepository).save(argThat(role ->
                RbacService.ROLE_ADMIN.equals(role.getName())
                        && "System administrator"
                        .equals(role.getDescription())
        ));

        verify(roleRepository, times(3)).save(any(Role.class));
    }

    @Test
    void initializeRoles_shouldNotCreateExistingRoles() {

        when(roleRepository.existsByName(anyString()))
                .thenReturn(true);

        rbacService.initializeRoles();

        verify(roleRepository, never()).save(any(Role.class));
    }

    @Test
    void assignDefaultUserRole_shouldCreateRoleAssignmentWhenMissing() {

        Long userId = 10L;
        Long roleId = 3L;

        Role role = new Role();
        role.setName(RbacService.ROLE_USER);

        // Role ID is normally generated by JPA.
        // Reflection is used here only to prepare the test fixture.
        setRoleId(role, roleId);

        when(roleRepository.findByName(RbacService.ROLE_USER))
                .thenReturn(Optional.of(role));

        when(userRoleRepository.existsByUserIdAndRoleId(
                userId,
                roleId
        )).thenReturn(false);

        rbacService.assignDefaultUserRole(userId);

        ArgumentCaptor<UserRole> captor =
                ArgumentCaptor.forClass(UserRole.class);

        verify(userRoleRepository).save(captor.capture());

        UserRole saved = captor.getValue();

        assertEquals(userId, saved.getUserId());
        assertEquals(roleId, saved.getRoleId());
    }

    @Test
    void assignDefaultUserRole_shouldNotDuplicateExistingAssignment() {

        Long userId = 10L;
        Long roleId = 3L;

        Role role = new Role();
        role.setName(RbacService.ROLE_USER);
        setRoleId(role, roleId);

        when(roleRepository.findByName(RbacService.ROLE_USER))
                .thenReturn(Optional.of(role));

        when(userRoleRepository.existsByUserIdAndRoleId(
                userId,
                roleId
        )).thenReturn(true);

        rbacService.assignDefaultUserRole(userId);

        verify(userRoleRepository, never())
                .save(any(UserRole.class));
    }

    @Test
    void assignDefaultUserRole_shouldFailWhenUserRoleIsNotInitialized() {

        Long userId = 10L;

        when(roleRepository.findByName(RbacService.ROLE_USER))
                .thenReturn(Optional.empty());

        IllegalStateException exception =
                assertThrows(
                        IllegalStateException.class,
                        () -> rbacService.assignDefaultUserRole(userId)
                );

        assertEquals(
                "ROLE_USER not initialized",
                exception.getMessage()
        );

        verify(userRoleRepository, never())
                .save(any(UserRole.class));
    }

    private void setRoleId(Role role, Long id) {

        try {
            var field = Role.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(role, id);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(
                    "Unable to prepare Role test fixture",
                    e
            );
        }
    }
}
